drop table if exists PRODUCT;

create table PRODUCT(
    ID INTEGER NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    PRICE DECIMAL NOT NULL,
    STOCK INTEGER NOT NULL,
    SELLER VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(128) NOT NULL,
    SUBCATEGORY VARCHAR(128) NOT NULL,
    FIT VARCHAR(128),
    MATERIAL VARCHAR(128),
    PRODTYPE VARCHAR(128),
    PICTUREURL VARCHAR(150) NOT NULL
);